Petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('pets/', include('pets.urls')),
    path('accounts/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/urls.py
from django.urls import path
from pets.views import \
    list_pets,\
    show_pet_detail,\
    like_pet,\
    create_pet,\
    edit_pet,\
    delete_pet

urlpatterns = [
    path('', list_pets, name='list pets'),
    path('create/', create_pet, name='create pet'),
    path('edit/<int:pk>', edit_pet, name='edit pet'),
    path('delete/<int:pk>', delete_pet, name='delete pet'),
    path('details/<int:pk>', show_pet_detail, name='pet details or comment'),
    path('like/<int:pk>', like_pet, name='like pet')
]

pets/models/comment.py
from django.db import models

from account.models import UserProfile
from pets.models.pet import Pet


class Comment(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    comment = models.TextField(blank=False)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

pets/models/like.py
from django.db import models

from account.models import UserProfile
from pets.models.pet import Pet


class Like(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

templates/landing_page.html
{% extends 'shared.html' %}
{% block site_content %}
  <div class="container">
     <div class="jumbotron parent">
        <img style="width: 100%" src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="absolute">
           <h1 class="display-4">Welcome to Petstagram</h1>
           <p class="lead">Share your pets photos.</p>
           <hr class="my-4">
           <div class="inner cover">
              <h1 class="cover-heading"></h1>
              <div class="row">
                 <div class="col-lg-6">
                    <p class="lead">Already have an account? <br><a href="{% url 'login' %}" class="btn btn-lg btn-secondary">sign in</a></p>
                 </div>
                 <div class="col-lg-6">
                    <p class="lead"> Do not have an account? <br>
                       <a href="{% url 'user signup' %}" class="btn btn-lg btn-secondary">sign up</a>
                    </p>
                 </div>
              </div>
           </div>
        </div>
     </div>
  </div>
{% endblock %}

templates/pet_create.html
{% extends 'shared.html' %}

{% block site_content %}
    <div class="container">
        <h1 class="text-center">Add new pet photo</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form method="post" class="furniture-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ create_form }}
                    <button class="btn btn-primary mt-2" type="submit">Create</button>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
{% endblock %}

templates/pet_delete.html
{% extends 'shared.html' %}

{% block site_content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1>Are you sure you want to delete {{ pet.name }}?</h1>
                <div class="m-auto d-flex justify-content-center">
                         <div class="m-2">
                             <form method="post" action="{% url 'delete pet' pet.id %}">
                                {% csrf_token %}
                                    <input type="submit" value="Confirm" class="btn btn-danger" />
                             </form>
                        </div>
                        <div class="m-2">
                            <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pet_detail.html
{% extends 'shared.html' %}

{% block site_content %}
    <div class="container">
            <div class="d-flex">
                <div class="d-inline p-2 w-50">
                    <img src="{{ pet.image.url }}" class="w-50 rounded mx-auto d-block">
                </div>
                <div class="d-inline p-2 w-50">
                    <div class="d-flex justify-content-between">
                        <h5><u>Type:</u> {{ pet.type }}</h5>
                        <h5><u>Name:</u> {{ pet.name }}</h5>
                        <h5><u>Age:</u> {{ pet.age }}</h5>
                        <h5><u>Owner:</u> <a href="{% url 'user profile' pet.user.user_id %}">{{ pet.user.user.username }}</a></h5>
                    </div>
                    <p class="mt-2">Description: {{ pet.description }}</p>
                    <div>
                        {% if can_edit %}
                            <a href="{% url 'edit pet' pet.id %}" class="btn btn-success">Edit</a>
                        {% endif %}
                        {% if can_delete %}
                            <a href="{% url 'delete pet' pet.id %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                    {% if can_like %}
                        {% if has_liked %}
                            <a href="{% url 'like pet' pet.id %}"><i class="fa fa-heart" aria-hidden="true"></i></a>
                        {% else %}
                            <a href="{% url 'like pet' pet.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                        {% endif %}
                        <p class="mt-2">Likes: {{ pet.like_set.count }}</p>

                    {% endif %}
                </div>
            </div>
    </div>
    <div class="d-block" style="background-color: #f1e3e3; padding:2%">
        {% if pet.comment_set.count > 0 %}
            {% for comment in pet.comment_set.all %}
                <div class="box">
                    <h5><em>{{ comment.comment }}</em></h5>
                    <hr>
                </div>
            {% endfor %}
            {% else %}
                <div class="box">
                    <h3>There are no comments for this pet. </h3>
                </div>
        {% endif %}

        {% if can_comment %}
            <div class="box">
                <form method="post" action="{% url 'pet details or comment' pet.id %}">
                    {% csrf_token %}
                    {{ comment_form }}
                    <button class="btn btn-primary mt-2" type="submit">Add comment</button>
                </form>
            </div>
        {% endif %}

    </div>
{% endblock %}

templates/pet_edit.html
{% extends 'shared.html' %}

{% block site_content %}
    <div class="container">
            <h1 class="text-center">Edit pet photo</h1>
            <div class="row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6">
                    <form method="post" class="furniture-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn btn-primary mt-2" type="submit">Edit</button>
                    </form>
                </div>
                <div class="col-lg-3"></div>
            </div>
    </div>
{% endblock %}

templates/pet_list.html
{% extends 'shared.html' %}

{% block site_content %}
    <div class="container">
            <h1 class='text-center'>All pet photos</h1>
            <div class="row">
                {% for pet in pets %}
                    <div class="col-lg-4">
                        <div class="card" style="width: 18rem;">
                            <img src="{{ pet.image.url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</h5>
                                <p class="card-text">{{ pet.description }}</p>
                                <a href="{% url 'pet details or comment' pet.id %}" class="btn btn-primary">See details</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
    </div>
{% endblock %}

templates/shared.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <a class="nav-link" href="/">Home</a>
            <a class="nav-link" href="{% url 'list pets' %}">All pets</a>
            <a class="nav-link" href="{% url 'create pet' %}">Add pet</a>
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'user profile' user.id %}">{{ user.username }}</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'user signout' %}">Sign out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Sign in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user signup' %}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block site_content %}

{% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>
</html>